name: Bug report
description: open a bug report.
title: "[Bug]:"
labels: ["bug"]
projects: ["tinteeam/tinos_version2"]
assignees: 
  - randomusert
body:
  - type: markdown
    attributes:
      value: |
        Please fill this bug report!
  - type: textarea
    id: what-happened
    attributes:
       label: What happened?
       description: what did you expect?
       value: "A bug happened!"
    validations:
      required: true
