
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '39 6 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'due to inactivity we are closing the issue soon'
        stale-pr-message: 'Stale pull request message'
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
